# Generated by Django 3.2.16 on 2023-04-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wuliu', '0001_squashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wuliu.permissiongroup', verbose_name='父权限组'),
        ),
        migrations.AlterField(
            model_name='permissiongroup',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wuliu.permissiongroup', verbose_name='父权限组'),
        ),
        migrations.AlterField(
            model_name='waybill',
            name='cargo_price_status',
            field=models.SmallIntegerField(choices=[(0, '无代收'), (1, '未支付'), (2, '已支付')], db_index=True, verbose_name='代收款状态'),
        ),
    ]
